---
- name: update apt cache
  apt:
    update_cache: True
    cache_valid_time: 3600

- name: reset grub on libvirt
  shell: echo "set grub-pc/install_devices /dev/vda" | debconf-communicate
  when: ansible_system_vendor == "QEMU"

- name: perform a dist-upgrade
  apt:
    upgrade: dist
    autoclean: True
    autoremove: True
  when: common_upgrade_base | bool

- name: install baseline dependencies
  apt:
    name: "{{ common_debs }}"
    state: latest

- name: install extra debs
  apt:
    name: "{{ common_extra_debs }}"
    state: latest

- name: install specific version of urllib3
  pip:
    name: urllib3==1.23
  when: ansible_distribution_version == "16.04"
