---
common_enable: True
common_upgrade_base: True
common_rpms:
- yum-utils
- python2-pip
- python2-requests
- ebtables
- socat
- ntp
- jq
- nfs-utils
- cloud-utils
- bind-utils
- firewalld
common_extra_rpms: []
common_debs:
- openssh-client
- openssh-server
- apt-transport-https
- python-pip
- python-requests
- ebtables
- socat
- ntp
- jq
- nfs-client
- cloud-utils
- dnsutils
- linux-generic-hwe-{{ansible_distribution_version}}
common_extra_debs: []
