- name: install kubeadm-selinux service
  template:
    src: etc/systemd/system/kubeadm-selinux.service.j2
    dest: /etc/systemd/system/kubeadm-selinux.service
    owner: root
    group: root
    mode: 0644

- name: install kubeadm-selinux timer
  copy:
    src: "{{ role_path }}/files/etc/systemd/system/kubeadm-selinux.timer"
    dest: "/etc/systemd/system/kubeadm-selinux.timer"
    owner: root
    group: root
    mode: 0644

- name: create directory for kubernetes specific policies
  file:
    path: /etc/selinux/containers
    state: directory

- name: copy container type enforcements
  copy:
    src: "{{ role_path }}/files/etc/selinux/containers/{{item}}.te"
    dest: "/etc/selinux/containers/{{item}}.te"
    owner: root
    group: root
    mode: 0644
  register: selinux_type_enforcement_containers
  with_items:
    - container_bpf
    - container_cert

- name: install container type enforcements into selinux
  shell: |
    checkmodule -M -m -o /etc/selinux/{{item}}.mod /etc/selinux/{{item}}.te && \
      semodule_package -o /etc/selinux/{{item}}.pp -m /etc/selinux/{{item}}.mod && \
      /usr/sbin/semodule -i /etc/selinux/{{item}}.pp
  with_items:
    - "containers/container_bpf"
    - "containers/container_cert"
  when: selinux_type_enforcement_containers.changed

- name: allow network connectivity for containers
  seboolean:
    name: container_connect_any
    state: yes
    persistent: yes

- name: give permission for containers to write to directories used by kubeadm
  sefcontext:
    target: "{{item}}(/.*)?"
    setype: container_file_t
    state: present
  with_items: "{{kubernetes_selinux_container_file_t}}"

- name: start the kubeadm-selinux service
  systemd:
    name: kubeadm-selinux
    state: started
    enabled: yes
    daemon_reload: yes

- name: enable the kubeadm-selinux timer
  systemd:
    name: kubeadm-selinux.timer
    state: started
    enabled: yes
    daemon_reload: yes
