---
# For RedHat, the version number will not be 2 decimal places. This is handled
# automatically in filter plugins
kubernetes_version: '1.14.1-00'
kubernetes_cni_version: '0.7.5-00'
kubernetes_cri_tools_version: '1.12.0-00'
kubernetes_enable_cached_images: False
kubernetes_cached_images: []
kubernetes_apt_repo_string: "deb http://apt.kubernetes.io/ {{ ansible_distribution_release | kube_debian_distro_version }} main"
kubernetes_yum_baseurl: 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64'
kubernetes_install_upstream_gpgkey: True
kubernetes_install_essential_pks_gpgkey: False
kubernetes_yum_gpgkey: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-kubernetes file:///etc/pki/rpm-gpg/RPM-GPG-KEY-kubernetes-packages'
kubernetes_disable_swap: True


