---
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: install kubernetes packages
  package:
    name:
     - kubelet
     - kubeadm
     - kubectl
     - kubernetes-cni
  register: kubernetes_install
  until: kubernetes_install is success
  retries: 5
  delay: 5

- name: set mandatory sysctl values for Kubernetes
  sysctl:
    name: "{{item.name}}"
    value: "{{item.value}}"
    sysctl_set: yes
    state: present
    reload: yes
  ignore_errors: "{{kubernetes_ignore_sysctl_errors}}"
  with_items:
  - name: net.bridge.bridge-nf-call-iptables
    value: "1"
  - name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
  - name: net.ipv4.ip_forward
    value: "1"
  # Settings here are normally set by kubelet, and allow a CIS benchmark to
  # pass
  - name: vm.overcommit_memory
    value: "1"
  - name: "kernel.panic"
    value: "10"
  - name: "kernel.panic_on_oops"
    value: "1"

- name: persist required kernel modules
  copy:
    content: |
      nf_conntrack
      br_netfilter
      ip_vs
      ip_vs_rr
      ip_vs_wrr
      ip_vs_sh
    dest: /etc/modules-load.d/kubernetes.conf

- name: remove swap mounts on boot
  mount:
    path: swap
    state: absent
  when: kubernetes_disable_swap|bool

- name: swapoff
  shell: /sbin/swapoff -a
  when: ansible_facts["memory_mb"]["swap"]["total"] > 0 and kubernetes_disable_swap|bool

- name: ensure that the kubelet is running
  service:
    name: kubelet
    state: started
    enabled: true

# Required by the docker_image ansible module
- name: install docker-py
  pip:
    name: docker-py
  when: kubernetes_enable_cached_images|bool and kubernetes_cached_images|length > 0

- name: cache docker images for kubeadm
  docker_image:
    name: "{{ item }}"
  with_items: kubernetes_cached_images
  when: kubernetes_enable_cached_images|bool and kubernetes_cached_images|length > 0

- name: set kubernetes version file
  copy:
    dest: /etc/kubernetes_community_ami_version
    content: "v{{ kubernetes_version.split('-')[0] }}"

