---
- name: lock docker version
  copy:
    dest: "/etc/apt/preferences.d/docker"
    content: |
      Package: {{docker_package}}
      Pin: version {{docker_debian_version}}*
      Pin-Priority: 1100
  when: docker_debian_version is defined
