---
- import_playbook: pre.yml
- name: build image
  hosts: all
  become: yes
  roles:
  - role: common
  - role: docker
  - role: kubernetes
  - role: providers
  - role: packer-cleanup
    when: packer_build_name is defined
