---

- name: update /etc/hosts to include cluster fqdn
  lineinfile:
    dest: /etc/hosts
    line: "{{ kubernetes_common_api_ip }} {{ kubernetes_common_api_fqdn }}"
    state: present
  when: kubernetes_common_manage_etc_hosts and kubernetes_common_api_ip is defined and kubernetes_common_api_fqdn is defined

- name: set kubernetes_node_ip fact
  set_fact:
    kubernetes_node_ip: "{{ hostvars[inventory_hostname]['ansible_'~item]['ipv4']['address'] }}"
  with_items:
    - "{{ kubernetes_common_primary_interface }}"
  when: kubernetes_common_primary_interface is defined

- name: drop kubeadm template
  template:
    src: etc/kubernetes/kubeadm.conf
    dest: /etc/kubernetes/kubeadm.conf

- name: flush handlers
  meta: flush_handlers
